version: "3"
services: 
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nginx-server
    restart: always
    ports:
      - 8080:80
    volumes: 
      - ./dist/PokedexUI:/usr/share/nginx/html/
volumes: 
  html: {}